<?php

/**
 * Implements hook_menu().
 */
function ckeditor_blocks_menu() {
  $items = array();

  $items['ckeditor/blocks'] = array(
    'page callback' => 'ckeditor_blocks_blocks_ajax',
    'access arguments' => array('administer blocks'),
  );
  $items['ckeditor/block/%/%'] = array(
    'page callback' => 'ckeditor_blocks_block_ajax',
    'page arguments' => array(2, 3),
    'access arguments' => array('administer blocks'),
  );

  return $items;
}

/**
 * Render a specific block
 */
function ckeditor_blocks_get_block($module, $delta, $check_roles = FALSE) {
  global $language;
  $block = block_custom_block_load($delta, $language->langcode);
  // Check user roles if required.
  // Ignoring this part for now
  if ($check_roles) {
    global $user;
    $block_roles = _ckeditor_blocks_roles();
    if (isset($block_roles[$block->module][$block->delta]) && !array_intersect($block_roles[$block->module][$block->delta], array_keys($user->roles))) {
      return '';
    }
  }

  $block_content = module_invoke($module, 'block_view', $delta);
  // print_r($block_content);exit;
  // Allow modules to modify the block before it is viewed, via either
  // hook_block_view_alter() or hook_block_view_MODULE_DELTA_alter().
  $block['subject'] = (empty($block_content['subject'])) ? '' : $block_content['subject'];
  backdrop_alter(array('block_view', "block_view_{$module}_" . str_replace('-', '_', $delta)), $block_content, $block);
  // print($block_content['content']);exit;
  if (isset($block_content['content'])) {
    // $render = array(
    //   'elements' => array(
    //     '#block' => $block,
    //     '#children' => render($block_content['content']),
    //   ),
    // );
     // Assemble a structured content array.
    $content = (object) array(
      'title' => $block['subject'],
      'content' => $block_content['content'],
    );
   // $output = theme('block', $render);
   $output = theme('block', array('content' => $content, 'block' => $block));
  }
  else {
    $output = '';
  }

  return $output;
}

/**
 * Page callback for getting a list of blocks.
 */
function ckeditor_blocks_blocks_ajax() {
  // Disable client-side caching.
  header('Cache-Control: private, no-cache, no-store, must-revalidate, max-age=0');
  header('Pragma: no-cache');
  // Disable server-side caching.
  backdrop_page_is_cacheable(FALSE);

  global $theme_key;
  $options = array();
  #$blocks = _block_rehash($theme_key);
  $module_blocks = layout_get_block_info();
  

  // Allow the block list to be altered.
  backdrop_alter('ckeditor_blocks_list', $module_blocks);
  //print_r($blocks);exit;
  // foreach ($blocks as $block) {
  //   print_r($block);
  //   exit;
  //   if ($block['module'] != 'system' || $block['delta'] != 'main') { // Don't allow main block because of recursion.
  //     $options['[block:' . $block['module'] . '=' . $block['delta'] . ']'] = $block['info'];
  //   }
  // }

  foreach ($module_blocks as $module => $blocks) {
    if (!empty($blocks)) {
      foreach ($blocks as $delta => $block) {
        $options['[block:' . $module. '=' . $delta . ']'] = $block['info'];
      }
    }
  }

  //print_r($options);exit;
  

//   $options = {
//     "[block:comment=recent]":"Recent comments",
//     "[block:node=syndicate]":"Syndicate",
//     "[block:node=recent]":"Recent content",
//     "[block:search=form]":"Search form",
//     "[block:shortcut=shortcuts]":"Shortcuts",
//     "[block:system=powered-by]":"Powered by Drupal",
//     "[block:system=help]":"System help",
//     "[block:system=navigation]":"Navigation",
//     "[block:system=management]":"Management",
//     "[block:system=user-menu]":"User menu",
//     "[block:system=main-menu]":"Main menu",
//     "[block:user=login]":"User login",
//     "[block:user=new]":"Who\u0027s new",
//     "[block:user=online]":"Who\u0027s online"
//  }
  backdrop_json_output($options);
}

/**
 * Page callback for rendering a block
 */
function ckeditor_blocks_block_ajax($module, $delta) {
  // Disable client-side caching.
  header('Cache-Control: private, no-cache, no-store, must-revalidate, max-age=0');
  header('Pragma: no-cache');
  // Disable server-side caching.
  backdrop_page_is_cacheable(FALSE);

  $block = ckeditor_blocks_get_block($module, $delta);

  backdrop_json_output(array('html' => ($block ? $block : '(Empty Block)')));
}

/**
 * Implements hook_ckeditor_plugin().
 *
 * @return type
 */
function ckeditor_blocks_ckeditor_plugins() {
//  $plugins = array();
//  $plugins['blocks'] = array(
//    // Plugin name.
//    'name' => 'blocks',
//    // Plugin description - it will be displayed in the plugins management
//    // section of the profile settings.
//    'desc' => t('Plugin for adding Backdrop blocks within CKEditor'),
//    // The full path to the CKEditor plugin directory, trailing slash included.
//    'path' => base_path() . backdrop_get_path('module', 'ckeditor_blocks') . '/plugins/blocks/',
//    // Plugin buttons definition (optional).
//      'file' => 'plugin.js',
//    'buttons' => array(
//      'Blocks' => array(
//        'label' => 'Block',
//        'icon' => 'icons/blocks.png',
//      ),
//    ),
//  );
//    echo '<pre>';
//    print_r($plugins); die;
//  return $plugins;
    $plugins['blocks'] = array(
        'path' => backdrop_get_path('module', 'ckeditor_blocks') . '/plugins/blocks',
        'file' => 'plugin.js',
        'internal' => FALSE,
        'buttons' => array(
            'Blocks' => array(
                'label' => t('Blocks'),
                'image' => base_path() . backdrop_get_path('module', 'ckeditor_blocks') . '/plugins/blocks/icons/blocks.png',
                'image_alternative' =>'{insert block}',
            ),
        ),
    );
//    echo '<pre>';
//    print_r($plugins); die;
    return $plugins;
}

/**
 * Implements hook_filter_info().
 */
function ckeditor_blocks_filter_info() {
  $filters['ckeditor_blocks'] = array(
    'title' => t('Backdrop blocks'),
    'description' => t('Inserts the contents of a block into a textarea using [block:module=delta] tags.'),
    'process callback' => '_ckeditor_blocks',
    'settings callback' => '_ckeditor_blocks_settings',
    'tips callback' => '_ckeditor_blocks_tips',
    'default settings' => array(
      'check_roles' => 0,
    ),
    'cache' => FALSE,
  );
  return $filters;
}

/**
 * Filter replacement callback.
 *
 * @param type $text
 * @param type $filter
 * @param type $format
 * @return type
 */
function _ckeditor_blocks($text, $filter, $format) {
  if (preg_match_all("/\[block:([^=\\]]+)=?([^\\]]*)?\]/i", $text, $match)) {
    foreach ($match[2] as $key => $value) {
      $raw_tags[] = $match[0][$key];
      $module = $match[1][$key];
      $delta = $match[2][$key];

      $check_roles = !empty($filter->settings['check_roles']);
      $repl[] =  ckeditor_blocks_get_block($module, $delta, $check_roles);
    }
    return str_replace($raw_tags, $repl, $text);
  }
  return $text;
}

/**
 * Settings callback for the backdrop block filter.
 */
function _ckeditor_blocks_settings($form, &$form_state, $filter, $format, $defaults=null) {
//  $filter->settings += $defaults;
  $settings['check_roles'] = array(
    '#type' => 'checkbox',
    '#title' => t('Check the roles assigned by the Block module'),
    '#default_value' => $filter->settings['check_roles'],
    '#description' => t('Without this checked, anyone can see backdrop blocks.'),
  );
  return $settings;
}

function _ckeditor_blocks_tips($filter, $format, $long = FALSE) {
  if ($long) {
    return t('<a name="filter-ckeditor_blocks"></a>You may use [block:<em>module</em>=<em>delta</em>] tags to display the contents of block <em>delta</em> for module <em>module</em>. To discover module names and deltas, visit admin/build/block and hover over a block\'s configure link and look in your browser\'s status bar. The last "word" you see is the name of the module and the number following that is the delta. If you leave off the delta in an Insert Block tag, the default delta will be used.');
  }
  else {
    return t('You may use <a href="@ckeditor_blocks_help">[block:<em>module</em>=<em>delta</em>] tags</a> to display the contents of block <em>delta</em> for module <em>module</em>.',
    array("@ckeditor_blocks_help" => url("filter/tips/$format->format", array('fragment' => 'filter-ckeditor_blocks'))));
  }
}

/**
 * Helper function to load and cache the block roles.
 */
function _ckeditor_blocks_roles() {
  // Build an array of roles for each block.
  $block_roles = &backdrop_static(__FUNCTION__, NULL);
  if (!isset($block_roles)) {
    $block_roles = array();
    $result = db_query('SELECT module, delta, rid FROM {block_role}');
    foreach ($result as $record) {
      $block_roles[$record->module][$record->delta][] = $record->rid;
    }
  }
  return $block_roles;
}

/**
 * Loads a block object from the database.
 *
 * This function returns the first block matching the module and delta
 * parameters, so it should not be used for theme-specific functionality.
 *
 * @param $module
 *   Name of the module that implements the block to load.
 * @param $delta
 *   Unique ID of the block within the context of $module. Pass NULL to return
 *   an empty block object for $module.
 *
 * @return
 *   A block object.
 */
function block_load($module, $delta) {
    $options = array();
    $blocks = layout_get_block_info()['block'];
    foreach ($blocks as $key => $block) {
        $options['block' . '|' . $key] = $block['info'];
    }
    asort($options);
}